language: csharp
script:
  - xbuild /p:Configuration=Debug "BizTalk Orchestration Profiler.sln"
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore "BizTalk Orchestration Profiler.sln"
after_script:
  - nunit-console Tests/bin/Debug/Tests.dll